name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update contribution snake"
          file_pattern: "dist/github-contribution-grid-snake.svg"
